// packages/vue-app/src/components/Signup.vue
<template>
    <div class="container-center"> 
        <img src="https://vuejs.org/images/logo.png" alt="VueJS logo" width="100" />
        <h1>This is Vue 3 application !</h1>
        <h2>Vue 3 Internal link</h2>
        <router-link to="/">Back to homepage</router-link>
    </div>
</template>



<script>

export default {   
}
</script>
<style scoped>
.container-center{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
</style>

// packages/react-app/src/components/Signup.js
import React from 'react';
import { Link } from 'react-router-dom';
import './style.css'
export default function SignUp({ onSignIn }) {

  return (
    <div className="container-center"> 
    <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" width="100"/>
    <h1>This is React 17 application !</h1>
    <h2>React internal page</h2>
    <Link to='/'>Internal link</Link>
    </div>
  );
}
